# Hydra Configuration for convert_dataset.py

defaults:
  - dataset: gsm8k # Points to project_root/conf/dataset/gsm8k.yaml by default
  # To use a different dataset, override from CLI:
  # python examples/math_example/convert_dataset.py dataset=custom_jsonl_dataset
  # Ensure 'custom_jsonl_dataset.yaml' exists in project_root/conf/dataset/
  - _self_ # Allows this file to override values from the chosen dataset config

hydra:
  run:
    # Hydra's output directory, can be overridden.
    # Default is outputs/YYYY-MM-DD/HH-MM-SS relative to the launch directory.
    # When running from project root: reward-kit/outputs/...
    dir: ./outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  job_logging:
    root:
      level: INFO
  sweep: # Default sweeper config
    dir: ./multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}

# The 'dataset' group will be populated by Hydra based on the 'defaults' above.
# It will contain the resolved configuration from, e.g., project_root/conf/dataset/gsm8k.yaml.
# Parameters like 'source_type', 'path_or_name', 'split', 'column_mapping', etc.,
# will come from that global dataset config.
# You can override specific dataset parameters here or from the command line.
# For example, to override the split for the chosen dataset:
# dataset:
#   split: "test"
#   max_samples: 100

# Parameters for processing the dataset (these are specific to this conversion script)
processing:
  filter_by_match: false              # Enable filtering by matching solution to ground truth
  math_type: "numeric"                # Type of math reward for filtering: "numeric", "mcq", "list"

# Parameters for the output
output:
  # Path for the output JSONL file.
  # If relative, it will be inside Hydra's output directory (hydra.run.dir).
  # If absolute, it will be used as is.
  file_path: "converted_dataset.jsonl"

# Removed old sections:
# - dataset_config_name: (now handled by `defaults: - dataset: ...`)
# - dataset_usage: (parameters like split, config_name, column names are now part of the global dataset config)
