base_resource_config:
  initial_config:
    TicketAPI:
      current_user: Michael Thompson
      ticket_counter: 2
      ticket_queue: []
    TradingBot:
      account_info:
        account_id: 12345
        balance: 10000.0
        binding_card: 1974202140965533
      authenticated: true
      market_status: Open
      order_counter: 12446
      stocks:
        AAPL:
          MA(20): 227.09
          MA(5): 227.11
          percent_change: 0.17
          price: 227.16
          volume: 2.552
        ALPH:
          MA(20): 1325.78
          MA(5): 1321.12
          percent_change: -0.08
          price: 1320.45
          volume: 1.567
        GOOG:
          MA(20): 2842.15
          MA(5): 2835.67
          percent_change: 0.24
          price: 2840.34
          volume: 1.123
        MSFT:
          MA(20): 310.11
          MA(5): 309.88
          percent_change: 0.09
          price: 310.23
          volume: 3.234
        NEPT:
          MA(20): 88.67
          MA(5): 88.21
          percent_change: 0.19
          price: 88.34
          volume: 0.654
        NVDA:
          MA(20): 220.67
          MA(5): 220.45
          percent_change: 0.34
          price: 220.34
          volume: 1.234
        OMEG:
          MA(20): 458.12
          MA(5): 456.78
          percent_change: 0.12
          price: 457.23
          volume: 2.345
        QUAS:
          MA(20): 728.0
          MA(5): 726.45
          percent_change: -0.03
          price: 725.89
          volume: 1.789
        SYNX:
          MA(20): 346.12
          MA(5): 345.34
          percent_change: 0.11
          price: 345.67
          volume: 2.112
        TSLA:
          MA(20): 668.2
          MA(5): 671.15
          percent_change: -0.12
          price: 667.92
          volume: 1.654
        ZETA:
          MA(20): 150.1
          MA(5): 149.75
          percent_change: 0.25
          price: 150.0
          volume: 1.5
      transaction_history: []
      watch_list:
      - NVDA
  involved_classes:
  - TradingBot
  - TicketAPI
description: 'BFCL task: [[{"role": "user", "content": "I''m contemplating whether
  adding Zeta Corp''s stock to my watchlist is the right move. It sounds like it''s
  on a noteworthy upward trend. Could you add that to my watchlist?"}], [{"role":
  "user", "content": "I''m gearing up to critique some financial strategies. Could
  you assist by checking the balance of my account and confirming which card I''m
  utilizing?"}], [{"role": "user", "content": "I''ve already reached out to support
  concerning the order issue, but still no word. Can you craft a ticket labeled ''Critical
  Order Assistance''? Make sure to encapsulate the order details and craft a concise
  case summary with message ''Urgent assistance required.'' for the support team''s
  assessment. Set to max priority."}], [{"role": "user", "content": "Since I''ve tackled
  the problem on my own, go ahead and resolve the ticket regarding the order inquiry,
  noting that it was ''Self-resolved, no longer requiring assistance.''"}]]'
evaluation_criteria:
  ground_truth_comparable_state:
    TicketAPI:
      current_user: Michael Thompson
      ticket_counter: 3
      ticket_queue:
      - created_by: Michael Thompson
        description: Urgent assistance required.
        id: 2
        priority: 5
        resolution: Self-resolved, no longer requiring assistance.
        status: Resolved
        title: Critical Order Assistance
    TradingBot:
      account_info:
        account_id: 12345
        balance: 10000.0
        binding_card: 1974202140965533
      authenticated: true
      long_context: false
      market_status: Open
      order_counter: 12446
      orders:
        12345:
          amount: 10
          id: 12345
          order_type: Buy
          price: 210.65
          status: Completed
          symbol: AAPL
        12446:
          amount: 5
          id: 12446
          order_type: Sell
          price: 2840.56
          status: Pending
          symbol: GOOG
      stocks:
        AAPL:
          MA(20): 227.09
          MA(5): 227.11
          percent_change: 0.17
          price: 227.16
          volume: 2.552
        ALPH:
          MA(20): 1325.78
          MA(5): 1321.12
          percent_change: -0.08
          price: 1320.45
          volume: 1.567
        GOOG:
          MA(20): 2842.15
          MA(5): 2835.67
          percent_change: 0.24
          price: 2840.34
          volume: 1.123
        MSFT:
          MA(20): 310.11
          MA(5): 309.88
          percent_change: 0.09
          price: 310.23
          volume: 3.234
        NEPT:
          MA(20): 88.67
          MA(5): 88.21
          percent_change: 0.19
          price: 88.34
          volume: 0.654
        NVDA:
          MA(20): 220.67
          MA(5): 220.45
          percent_change: 0.34
          price: 220.34
          volume: 1.234
        OMEG:
          MA(20): 458.12
          MA(5): 456.78
          percent_change: 0.12
          price: 457.23
          volume: 2.345
        QUAS:
          MA(20): 728.0
          MA(5): 726.45
          percent_change: -0.03
          price: 725.89
          volume: 1.789
        SYNX:
          MA(20): 346.12
          MA(5): 345.34
          percent_change: 0.11
          price: 345.67
          volume: 2.112
        TSLA:
          MA(20): 668.2
          MA(5): 671.15
          percent_change: -0.12
          price: 667.92
          volume: 1.654
        ZETA:
          MA(20): 150.1
          MA(5): 149.75
          percent_change: 0.25
          price: 150.0
          volume: 1.5
      transaction_history: []
      watch_list:
      - NVDA
      - ZETA
  ground_truth_function_calls:
  - - add_to_watchlist(stock='ZETA')
  - - get_account_info()
  - - create_ticket(title='Critical Order Assistance',description='Urgent assistance
      required.',priority=5)
  - - resolve_ticket(ticket_id=2,resolution='Self-resolved, no longer requiring assistance.')
messages:
- content: '[{"role": "user", "content": "I''m contemplating whether adding Zeta Corp''s
    stock to my watchlist is the right move. It sounds like it''s on a noteworthy
    upward trend. Could you add that to my watchlist?"}]'
  role: user
- content: I'm gearing up to critique some financial strategies. Could you assist
    by checking the balance of my account and confirming which card I'm utilizing?
  role: user
- content: I've already reached out to support concerning the order issue, but still
    no word. Can you craft a ticket labeled 'Critical Order Assistance'? Make sure
    to encapsulate the order details and craft a concise case summary with message
    'Urgent assistance required.' for the support team's assessment. Set to max priority.
  role: user
- content: Since I've tackled the problem on my own, go ahead and resolve the ticket
    regarding the order inquiry, noting that it was 'Self-resolved, no longer requiring
    assistance.'
  role: user
name: multi_turn_base_140
resource_type: BFCLSimAPIResource
reward_function_path: reward_kit.rewards.bfcl_reward
