base_resource_config:
  initial_config:
    TravelAPI:
      access_token: abc123xyz
      booking_record: {}
      budget_limit: 10000.0
      credit_card_list:
        primary:
          balance: 5000.0
          card_number: '4111111111111111'
          cardholder_name: Eleanor Smith
          expiry_date: 12/25
      token_expires_in: 3600
      token_scope: read write
      token_type: Bearer
      user_first_name: Eleanor
      user_last_name: Smith
  involved_classes:
  - TicketAPI
  - TravelAPI
description: 'BFCL task: [[{"role": "user", "content": "Check the verification of
  Eleanor Smith''s personal details, including her date of birth, March 15, 1985,
  and her passport number US123456789."}], [{"role": "user", "content": "Identify
  the closest airport to Crescent Hollow."}], [{"role": "user", "content": "Arrange
  a flight reservation to the nearest airport in Hong Kong, with the departure date
  set for December 15, 2024, in economy class at a cost of $850, using the credit
  card labeled ''primary'' and access token ''abc123xyz'' on file, ensuring all personal
  information is verified and protected. Make sure the budget limit is 1000."}], [{"role":
  "user", "content": "Locate and provide the travel invoice that has gone missing
  for review of the transaction details."}], [{"role": "user", "content": "Contact
  customer support urgently to report and resolve a discrepancy encountered with the
  booking, providing all necessary details."}]]'
evaluation_criteria:
  ground_truth_comparable_state:
    TicketAPI:
      current_user: null
      ticket_counter: 1
      ticket_queue: []
    TravelAPI:
      access_token: abc123xyz
      booking_record:
        '3426812':
          card_id: primary
          transaction_id: '45451592'
          travel_class: economy
          travel_cost: 850.0
          travel_date: '2024-12-15'
          travel_from: CRH
          travel_to: HKG
      budget_limit: 1000.0
      credit_card_list:
        primary:
          balance: 4150.0
          card_number: '4111111111111111'
          cardholder_name: Eleanor Smith
          expiry_date: 12/25
      long_context: false
      token_expires_in: 3600
      token_scope: read write
      token_type: Bearer
      user_first_name: Eleanor
      user_last_name: Smith
  ground_truth_function_calls:
  - - verify_traveler_information(first_name='Eleanor', last_name='Smith', date_of_birth='1985-03-15',
      passport_number='US123456789')
  - - get_nearest_airport_by_city(location='Crescent Hollow')
  - - set_budget_limit(access_token='abc123xyz',budget_limit=1000)
    - book_flight(access_token='abc123xyz', card_id='primary', travel_date='2024-12-15',
      travel_from='CRH', travel_to='HKG', travel_class='economy', travel_cost=850.0)
  - - retrieve_invoice(access_token='abc123xyz', booking_id='3426812')
  - - 'contact_customer_support(booking_id=''3426812'', message=''Urgent: Discrepancy
      encountered with the booking. Please resolve.'')'
messages:
- content: '[{"role": "user", "content": "Check the verification of Eleanor Smith''s
    personal details, including her date of birth, March 15, 1985, and her passport
    number US123456789."}]'
  role: user
- content: Identify the closest airport to Crescent Hollow.
  role: user
- content: Arrange a flight reservation to the nearest airport in Hong Kong, with
    the departure date set for December 15, 2024, in economy class at a cost of $850,
    using the credit card labeled 'primary' and access token 'abc123xyz' on file,
    ensuring all personal information is verified and protected. Make sure the budget
    limit is 1000.
  role: user
- content: Locate and provide the travel invoice that has gone missing for review
    of the transaction details.
  role: user
- content: Contact customer support urgently to report and resolve a discrepancy encountered
    with the booking, providing all necessary details.
  role: user
name: multi_turn_base_165
resource_type: BFCLSimAPIResource
reward_function_path: reward_kit.rewards.bfcl_reward
