# Hydra Configuration for examples/tool_calling_example/trl_grpo_integration.py

hydra:
  run:
    dir: ./outputs/trl_grpo_tool_calling/${now:%Y-%m-%d}/${now:%H-%M-%S}
  job_logging:
    root:
      level: INFO

# Path to the processed dataset file (JSONL format) for TRL training
dataset_file_path: "dataset.jsonl" # Default, assumes dataset.jsonl is in the same dir as the script

# Model name
model_name: "Qwen/Qwen2-0.5B-Instruct"

# GRPOConfig settings
grpo:
  learning_rate: 1.41e-5 # Example value
  beta: 0.1 # Example value
  num_train_epochs: 1 # Example value
  max_steps: 5 # Example value, 1 if test_mode_trl=true
  logging_steps: 1 # Example value
  per_device_train_batch_size: 2 # Example value, may need adjustment based on data/model
  gradient_accumulation_steps: 1 # Example value
  max_completion_length: 100 # Example value, for tool calling, might need more tokens
  top_k: 0.0
  top_p: 1.0
  do_sample: True

# Test mode flag
test_mode_trl: false
