base_resource_config:
  initial_config:
    TravelAPI:
      access_token: abc123xyz
      booking_record:
        booking001:
          class: Business
          date: '2024-12-15'
          departure: Rivermist
          destination: Los Angeles
          flight_number: LA123
          price: 1500.0
      budget_limit: 5000.0
      credit_card_list:
        card1234:
          balance: 10000.0
          card_number: 1234-5678-9012-3456
          cardholder_name: Michael Thompson
          expiry_date: 12/25
      token_expires_in: 3600
      token_scope: read_write
      token_type: Bearer
      user_first_name: Michael
      user_last_name: Thompson
  involved_classes:
  - TravelAPI
description: 'BFCL task: [[{"role": "user", "content": "Before I start packing my
  bags for the upcoming trip, I need to double-check that all my personal information
  is up to date. Let''s go over my full name and passport details to make sure everything''s
  in order before I hit the road. For reference my birthdate is January 1st 1950 and
  the number on my passport is P followed by 12345678. My first name is Michael and  last
  name is Thompson"}], [{"role": "user", "content": "Now that my personal details
  have been sorted, I''m eager to locate the nearest airport to Rivermist. After that,
  I''d appreciate a price estimate for flying business class from there to GFD on
  December 15, 2024."}], [{"role": "user", "content": "Looking at the travel expenses,
  I''ve realized the importance of setting a spending cap. Could you help me establish
  a travel budget of $5000, so I can keep my finances in check using the access token
  abc123xyz?"}], [{"role": "user", "content": "Armed with my budget, I\u2019m ready
  to lock in my travel plans. Let\u2019s proceed with booking my flight from RMS to
  GFD, using my go-to credit card with id ''card1234''. I''d like to get everything
  in order for the transaction."}], [{"role": "user", "content": "Finally, to finalize
  my travel preparations, a neat summary of my booking would be amazing. Could you
  generate an invoice for this latest purchase? It would be great to review everything
  before I start packing."}]]'
evaluation_criteria:
  ground_truth_comparable_state:
    TravelAPI:
      access_token: abc123xyz
      booking_record:
        '3426812':
          card_id: card1234
          transaction_id: '45451592'
          travel_class: business
          travel_cost: 640.0
          travel_date: '2024-12-15'
          travel_from: RMS
          travel_to: GFD
        booking001:
          class: Business
          date: '2024-12-15'
          departure: Rivermist
          destination: Los Angeles
          flight_number: LA123
          price: 1500.0
      budget_limit: 5000.0
      credit_card_list:
        card1234:
          balance: 9360.0
          card_number: 1234-5678-9012-3456
          cardholder_name: Michael Thompson
          expiry_date: 12/25
      long_context: false
      token_expires_in: 3600
      token_scope: read_write
      token_type: Bearer
      user_first_name: Michael
      user_last_name: Thompson
  ground_truth_function_calls:
  - - verify_traveler_information(first_name='Michael', last_name='Thompson', date_of_birth='1950-01-01',
      passport_number='P12345678')
  - - get_flight_cost(travel_from='RMS', travel_to='GFD', travel_date='2024-12-15',
      travel_class='business')
  - - set_budget_limit(access_token='abc123xyz', budget_limit=5000)
  - - book_flight(access_token='abc123xyz', card_id='card1234', travel_date='2024-12-15',
      travel_from='RMS', travel_to='GFD', travel_class='business', travel_cost=640.0)
  - - retrieve_invoice(access_token='abc123xyz', booking_id='3426812')
messages:
- content: '[{"role": "user", "content": "Before I start packing my bags for the upcoming
    trip, I need to double-check that all my personal information is up to date. Let''s
    go over my full name and passport details to make sure everything''s in order
    before I hit the road. For reference my birthdate is January 1st 1950 and the
    number on my passport is P followed by 12345678. My first name is Michael and  last
    name is Thompson"}]'
  role: user
- content: Now that my personal details have been sorted, I'm eager to locate the
    nearest airport to Rivermist. After that, I'd appreciate a price estimate for
    flying business class from there to GFD on December 15, 2024.
  role: user
- content: Looking at the travel expenses, I've realized the importance of setting
    a spending cap. Could you help me establish a travel budget of $5000, so I can
    keep my finances in check using the access token abc123xyz?
  role: user
- content: "Armed with my budget, I\u2019m ready to lock in my travel plans. Let\u2019\
    s proceed with booking my flight from RMS to GFD, using my go-to credit card with\
    \ id 'card1234'. I'd like to get everything in order for the transaction."
  role: user
- content: Finally, to finalize my travel preparations, a neat summary of my booking
    would be amazing. Could you generate an invoice for this latest purchase? It would
    be great to review everything before I start packing.
  role: user
name: multi_turn_base_153
resource_type: BFCLSimAPIResource
reward_function_path: reward_kit.rewards.bfcl_reward
