# Hydra Configuration for examples/math_example_openr1/local_eval.py

hydra:
  run:
    dir: ./outputs/local_eval_openr1/${now:%Y-%m-%d}/${now:%H-%M-%S}
  job_logging:
    root:
      level: INFO

# Path to the processed dataset file (JSONL format)
# This path can be relative to the original CWD or absolute.
# Example: "dataset.jsonl" (if in the same dir as script is run from)
# or an output from convert_dataset.py e.g. "outputs/YYYY-MM-DD/HH-MM-SS/converted_dataset.jsonl"
dataset_file_path: "dataset.jsonl" # Default, can be overridden
